package libparser

import "fmt"

// A string that can have variable expansions inside.
// Uses backticks (`) instead of quotes.
type StringNode struct {
	Contents string

	// Holds segments generated by [libparser.StringFormatter]
	//
	// WARN: Parse() does NOT set it by default.
	// Used by other libraries such as `lib-validator` as part of post-processing
	Segments []Segment
}

func (node *StringNode) Node() string {
	return fmt.Sprintf("[string %q]", node.Contents)
}
